// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozzACO7xD5v8BAWqwIjqwwTosrqnCwWY',
    appId: '1:206482157759:web:c15b33be3f7a38ea8f960a',
    messagingSenderId: '206482157759',
    projectId: 'flutterapp-fb893',
    authDomain: 'flutterapp-fb893.firebaseapp.com',
    databaseURL: 'https://flutterapp-fb893-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-fb893.appspot.com',
    measurementId: 'G-6GVKTQ7C4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQsAx69WcWH7baCuGiuFED3A3BQx5-uQ',
    appId: '1:206482157759:android:0b84d5bef8ed40978f960a',
    messagingSenderId: '206482157759',
    projectId: 'flutterapp-fb893',
    databaseURL: 'https://flutterapp-fb893-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-fb893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuT8LpTmS4JXrxdStyLGojn5FNrrtHRw',
    appId: '1:206482157759:ios:b1da13bb648a33a28f960a',
    messagingSenderId: '206482157759',
    projectId: 'flutterapp-fb893',
    databaseURL: 'https://flutterapp-fb893-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-fb893.appspot.com',
    iosClientId: '206482157759-0hin9j28oq6afimd6ticl0u2b4rmcdd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNuT8LpTmS4JXrxdStyLGojn5FNrrtHRw',
    appId: '1:206482157759:ios:ed3ef1bddc73e4608f960a',
    messagingSenderId: '206482157759',
    projectId: 'flutterapp-fb893',
    databaseURL: 'https://flutterapp-fb893-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-fb893.appspot.com',
    iosClientId: '206482157759-uujb5kg7h0fhcmm10jk56610ur4iieih.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
